# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-10 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postt',
            name='content',
            field=models.TextField(verbose_name='i\xe7erik'),
        ),
        migrations.AlterField(
            model_name='postt',
            name='publishing_date',
            field=models.DateTimeField(verbose_name='yay\u0131nlanma tarihi'),
        ),
        migrations.AlterField(
            model_name='postt',
            name='title',
            field=models.CharField(max_length=120, verbose_name='ba\u015fl\u0131k'),
        ),
    ]
