# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-18 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postt', '0002_auto_20191010_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postt',
            name='publishing_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yay\u0131nlanma tarihi'),
        ),
    ]
