# Generated by Django 2.2.6 on 2019-10-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postt', '0003_auto_20191018_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='postt',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
