# Generated by Django 2.2.6 on 2019-10-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postt', '0004_postt_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postt',
            options={'ordering': ['publishing_date']},
        ),
        migrations.AlterField(
            model_name='postt',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
