# Generated by Django 2.2.6 on 2019-10-25 11:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postt', '0005_auto_20191025_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postt',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='içerik'),
        ),
    ]
