# Generated by Django 2.2.6 on 2019-10-25 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postt', '0006_auto_20191025_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='postt',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='yazar'),
            preserve_default=False,
        ),
    ]
