# Generated by Django 2.2.6 on 2019-10-30 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postt', '0008_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
