# Generated by Django 2.2.6 on 2019-11-20 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postt', '0011_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replys',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies2', to='postt.comment'),
        ),
    ]
